// Shared project data: a realistic software development project with complex dependencies

export const PROJECT_START = new Date(2026, 2, 1); // March 1, 2026

function d(month: number, day: number): Date {
  return new Date(2026, month, day);
}

// ─── Frappe Gantt Tasks ─────────────────────────────────────────────────────

export const frappeGanttTasks = [
  // Phase 1: Discovery & Planning
  {
    id: "discovery",
    name: "Discovery & Planning",
    start: "2026-03-02",
    end: "2026-03-20",
    progress: 100,
    custom_class: "phase",
    color: "#6366f1",
  },
  {
    id: "stakeholder",
    name: "Stakeholder Interviews",
    start: "2026-03-02",
    end: "2026-03-06",
    progress: 100,
    dependencies: "discovery",
    color: "#818cf8",
  },
  {
    id: "requirements",
    name: "Requirements Gathering",
    start: "2026-03-06",
    end: "2026-03-13",
    progress: 100,
    dependencies: "stakeholder",
    color: "#818cf8",
  },
  {
    id: "tech-assessment",
    name: "Technical Assessment",
    start: "2026-03-09",
    end: "2026-03-16",
    progress: 85,
    dependencies: "stakeholder",
    color: "#818cf8",
  },
  {
    id: "risk-analysis",
    name: "Risk Analysis",
    start: "2026-03-13",
    end: "2026-03-18",
    progress: 70,
    dependencies: "requirements",
    color: "#818cf8",
  },
  {
    id: "project-charter",
    name: "Project Charter Sign-off",
    start: "2026-03-18",
    end: "2026-03-20",
    progress: 50,
    dependencies: "risk-analysis, tech-assessment",
    color: "#4f46e5",
  },

  // Phase 2: Design
  {
    id: "design",
    name: "UX/UI Design",
    start: "2026-03-20",
    end: "2026-04-17",
    progress: 45,
    custom_class: "phase",
    color: "#ec4899",
  },
  {
    id: "wireframes",
    name: "Wireframes & User Flows",
    start: "2026-03-20",
    end: "2026-03-30",
    progress: 60,
    dependencies: "project-charter",
    color: "#f472b6",
  },
  {
    id: "design-system",
    name: "Design System Setup",
    start: "2026-03-25",
    end: "2026-04-04",
    progress: 40,
    dependencies: "wireframes",
    color: "#f472b6",
  },
  {
    id: "hi-fi-mockups",
    name: "High-Fidelity Mockups",
    start: "2026-03-30",
    end: "2026-04-10",
    progress: 30,
    dependencies: "wireframes",
    color: "#f472b6",
  },
  {
    id: "prototype",
    name: "Interactive Prototype",
    start: "2026-04-07",
    end: "2026-04-14",
    progress: 10,
    dependencies: "hi-fi-mockups, design-system",
    color: "#f472b6",
  },
  {
    id: "design-review",
    name: "Design Review & Approval",
    start: "2026-04-14",
    end: "2026-04-17",
    progress: 0,
    dependencies: "prototype",
    color: "#db2777",
  },

  // Phase 3: Backend Development
  {
    id: "backend",
    name: "Backend Development",
    start: "2026-04-06",
    end: "2026-05-22",
    progress: 20,
    custom_class: "phase",
    color: "#f59e0b",
  },
  {
    id: "db-schema",
    name: "Database Schema Design",
    start: "2026-04-06",
    end: "2026-04-13",
    progress: 50,
    dependencies: "requirements",
    color: "#fbbf24",
  },
  {
    id: "auth-service",
    name: "Auth & IAM Service",
    start: "2026-04-13",
    end: "2026-04-24",
    progress: 25,
    dependencies: "db-schema",
    color: "#fbbf24",
  },
  {
    id: "api-core",
    name: "Core API Endpoints",
    start: "2026-04-13",
    end: "2026-05-01",
    progress: 15,
    dependencies: "db-schema",
    color: "#fbbf24",
  },
  {
    id: "api-integration",
    name: "3rd Party Integrations",
    start: "2026-04-27",
    end: "2026-05-11",
    progress: 0,
    dependencies: "api-core",
    color: "#fbbf24",
  },
  {
    id: "backend-testing",
    name: "Backend Testing & QA",
    start: "2026-05-04",
    end: "2026-05-18",
    progress: 0,
    dependencies: "auth-service, api-core",
    color: "#d97706",
  },
  {
    id: "perf-optimization",
    name: "Performance Optimization",
    start: "2026-05-11",
    end: "2026-05-22",
    progress: 0,
    dependencies: "backend-testing",
    color: "#d97706",
  },

  // Phase 4: Frontend Development
  {
    id: "frontend",
    name: "Frontend Development",
    start: "2026-04-17",
    end: "2026-05-29",
    progress: 10,
    custom_class: "phase",
    color: "#10b981",
  },
  {
    id: "fe-scaffold",
    name: "Project Scaffolding",
    start: "2026-04-17",
    end: "2026-04-22",
    progress: 80,
    dependencies: "design-review",
    color: "#34d399",
  },
  {
    id: "fe-components",
    name: "Component Library",
    start: "2026-04-20",
    end: "2026-05-04",
    progress: 20,
    dependencies: "fe-scaffold, design-system",
    color: "#34d399",
  },
  {
    id: "fe-pages",
    name: "Page Implementation",
    start: "2026-05-01",
    end: "2026-05-15",
    progress: 0,
    dependencies: "fe-components, hi-fi-mockups",
    color: "#34d399",
  },
  {
    id: "fe-integration",
    name: "API Integration",
    start: "2026-05-11",
    end: "2026-05-22",
    progress: 0,
    dependencies: "fe-pages, api-core",
    color: "#34d399",
  },
  {
    id: "fe-testing",
    name: "Frontend Testing",
    start: "2026-05-18",
    end: "2026-05-29",
    progress: 0,
    dependencies: "fe-integration",
    color: "#059669",
  },

  // Phase 5: Launch
  {
    id: "launch",
    name: "Launch Preparation",
    start: "2026-05-25",
    end: "2026-06-12",
    progress: 0,
    custom_class: "phase",
    color: "#ef4444",
  },
  {
    id: "staging",
    name: "Staging Deployment",
    start: "2026-05-25",
    end: "2026-05-29",
    progress: 0,
    dependencies: "fe-testing, perf-optimization",
    color: "#f87171",
  },
  {
    id: "uat",
    name: "UAT Testing",
    start: "2026-05-29",
    end: "2026-06-05",
    progress: 0,
    dependencies: "staging",
    color: "#f87171",
  },
  {
    id: "bug-fixes",
    name: "Bug Fixes & Polish",
    start: "2026-06-01",
    end: "2026-06-08",
    progress: 0,
    dependencies: "uat",
    color: "#f87171",
  },
  {
    id: "prod-deploy",
    name: "Production Deployment",
    start: "2026-06-08",
    end: "2026-06-10",
    progress: 0,
    dependencies: "bug-fixes",
    color: "#dc2626",
  },
  {
    id: "go-live",
    name: "Go Live!",
    start: "2026-06-10",
    end: "2026-06-12",
    progress: 0,
    dependencies: "prod-deploy",
    color: "#b91c1c",
  },
];

// ─── gantt-task-react Tasks ─────────────────────────────────────────────────

export function getGanttTaskReactData() {
  return [
    // Project: Discovery & Planning
    {
      id: "proj-discovery",
      name: "Discovery & Planning",
      type: "project" as const,
      start: d(2, 2),
      end: d(2, 20),
      progress: 85,
      hideChildren: false,
      styles: { backgroundColor: "#6366f1", progressColor: "#4f46e5", backgroundSelectedColor: "#4338ca", progressSelectedColor: "#3730a3" },
    },
    {
      id: "stakeholder",
      name: "Stakeholder Interviews",
      type: "task" as const,
      start: d(2, 2),
      end: d(2, 6),
      progress: 100,
      project: "proj-discovery",
      dependencies: [],
      styles: { backgroundColor: "#818cf8", progressColor: "#6366f1", backgroundSelectedColor: "#6366f1", progressSelectedColor: "#4f46e5" },
    },
    {
      id: "requirements",
      name: "Requirements Gathering",
      type: "task" as const,
      start: d(2, 6),
      end: d(2, 13),
      progress: 100,
      project: "proj-discovery",
      dependencies: ["stakeholder"],
      styles: { backgroundColor: "#818cf8", progressColor: "#6366f1", backgroundSelectedColor: "#6366f1", progressSelectedColor: "#4f46e5" },
    },
    {
      id: "tech-assessment",
      name: "Technical Assessment",
      type: "task" as const,
      start: d(2, 9),
      end: d(2, 16),
      progress: 85,
      project: "proj-discovery",
      dependencies: ["stakeholder"],
      styles: { backgroundColor: "#818cf8", progressColor: "#6366f1", backgroundSelectedColor: "#6366f1", progressSelectedColor: "#4f46e5" },
    },
    {
      id: "risk-analysis",
      name: "Risk Analysis",
      type: "task" as const,
      start: d(2, 13),
      end: d(2, 18),
      progress: 70,
      project: "proj-discovery",
      dependencies: ["requirements"],
      styles: { backgroundColor: "#a5b4fc", progressColor: "#818cf8", backgroundSelectedColor: "#818cf8", progressSelectedColor: "#6366f1" },
    },
    {
      id: "charter-signoff",
      name: "Charter Sign-off",
      type: "milestone" as const,
      start: d(2, 20),
      end: d(2, 20),
      progress: 0,
      project: "proj-discovery",
      dependencies: ["risk-analysis", "tech-assessment"],
      styles: { backgroundColor: "#4f46e5", backgroundSelectedColor: "#3730a3", progressColor: "#4f46e5", progressSelectedColor: "#3730a3" },
    },

    // Project: Design
    {
      id: "proj-design",
      name: "UX/UI Design",
      type: "project" as const,
      start: d(2, 20),
      end: d(3, 17),
      progress: 35,
      hideChildren: false,
      styles: { backgroundColor: "#ec4899", progressColor: "#db2777", backgroundSelectedColor: "#be185d", progressSelectedColor: "#9d174d" },
    },
    {
      id: "wireframes",
      name: "Wireframes & User Flows",
      type: "task" as const,
      start: d(2, 20),
      end: d(2, 30),
      progress: 60,
      project: "proj-design",
      dependencies: ["charter-signoff"],
      styles: { backgroundColor: "#f472b6", progressColor: "#ec4899", backgroundSelectedColor: "#ec4899", progressSelectedColor: "#db2777" },
    },
    {
      id: "design-system",
      name: "Design System Setup",
      type: "task" as const,
      start: d(2, 25),
      end: d(3, 4),
      progress: 40,
      project: "proj-design",
      dependencies: ["wireframes"],
      styles: { backgroundColor: "#f472b6", progressColor: "#ec4899", backgroundSelectedColor: "#ec4899", progressSelectedColor: "#db2777" },
    },
    {
      id: "mockups",
      name: "High-Fidelity Mockups",
      type: "task" as const,
      start: d(2, 30),
      end: d(3, 10),
      progress: 30,
      project: "proj-design",
      dependencies: ["wireframes"],
      styles: { backgroundColor: "#f472b6", progressColor: "#ec4899", backgroundSelectedColor: "#ec4899", progressSelectedColor: "#db2777" },
    },
    {
      id: "prototype",
      name: "Interactive Prototype",
      type: "task" as const,
      start: d(3, 7),
      end: d(3, 14),
      progress: 10,
      project: "proj-design",
      dependencies: ["mockups", "design-system"],
      styles: { backgroundColor: "#f9a8d4", progressColor: "#f472b6", backgroundSelectedColor: "#f472b6", progressSelectedColor: "#ec4899" },
    },
    {
      id: "design-approval",
      name: "Design Approval",
      type: "milestone" as const,
      start: d(3, 17),
      end: d(3, 17),
      progress: 0,
      project: "proj-design",
      dependencies: ["prototype"],
      styles: { backgroundColor: "#db2777", backgroundSelectedColor: "#9d174d", progressColor: "#db2777", progressSelectedColor: "#9d174d" },
    },

    // Project: Backend
    {
      id: "proj-backend",
      name: "Backend Development",
      type: "project" as const,
      start: d(3, 6),
      end: d(4, 22),
      progress: 15,
      hideChildren: false,
      styles: { backgroundColor: "#f59e0b", progressColor: "#d97706", backgroundSelectedColor: "#b45309", progressSelectedColor: "#92400e" },
    },
    {
      id: "db-schema",
      name: "Database Schema Design",
      type: "task" as const,
      start: d(3, 6),
      end: d(3, 13),
      progress: 50,
      project: "proj-backend",
      dependencies: ["requirements"],
      styles: { backgroundColor: "#fbbf24", progressColor: "#f59e0b", backgroundSelectedColor: "#f59e0b", progressSelectedColor: "#d97706" },
    },
    {
      id: "auth-service",
      name: "Auth & IAM Service",
      type: "task" as const,
      start: d(3, 13),
      end: d(3, 24),
      progress: 25,
      project: "proj-backend",
      dependencies: ["db-schema"],
      styles: { backgroundColor: "#fbbf24", progressColor: "#f59e0b", backgroundSelectedColor: "#f59e0b", progressSelectedColor: "#d97706" },
    },
    {
      id: "api-core",
      name: "Core API Endpoints",
      type: "task" as const,
      start: d(3, 13),
      end: d(4, 1),
      progress: 15,
      project: "proj-backend",
      dependencies: ["db-schema"],
      styles: { backgroundColor: "#fbbf24", progressColor: "#f59e0b", backgroundSelectedColor: "#f59e0b", progressSelectedColor: "#d97706" },
    },
    {
      id: "integrations",
      name: "3rd Party Integrations",
      type: "task" as const,
      start: d(3, 27),
      end: d(4, 11),
      progress: 0,
      project: "proj-backend",
      dependencies: ["api-core"],
      styles: { backgroundColor: "#fcd34d", progressColor: "#fbbf24", backgroundSelectedColor: "#fbbf24", progressSelectedColor: "#f59e0b" },
    },
    {
      id: "backend-qa",
      name: "Backend Testing & QA",
      type: "task" as const,
      start: d(4, 4),
      end: d(4, 18),
      progress: 0,
      project: "proj-backend",
      dependencies: ["auth-service", "api-core"],
      styles: { backgroundColor: "#fde68a", progressColor: "#fcd34d", backgroundSelectedColor: "#fcd34d", progressSelectedColor: "#fbbf24" },
    },
    {
      id: "perf-opt",
      name: "Performance Optimization",
      type: "task" as const,
      start: d(4, 11),
      end: d(4, 22),
      progress: 0,
      project: "proj-backend",
      dependencies: ["backend-qa"],
      styles: { backgroundColor: "#fde68a", progressColor: "#fcd34d", backgroundSelectedColor: "#fcd34d", progressSelectedColor: "#fbbf24" },
    },

    // Project: Frontend
    {
      id: "proj-frontend",
      name: "Frontend Development",
      type: "project" as const,
      start: d(3, 17),
      end: d(4, 29),
      progress: 8,
      hideChildren: false,
      styles: { backgroundColor: "#10b981", progressColor: "#059669", backgroundSelectedColor: "#047857", progressSelectedColor: "#065f46" },
    },
    {
      id: "fe-scaffold",
      name: "Project Scaffolding",
      type: "task" as const,
      start: d(3, 17),
      end: d(3, 22),
      progress: 80,
      project: "proj-frontend",
      dependencies: ["design-approval"],
      styles: { backgroundColor: "#34d399", progressColor: "#10b981", backgroundSelectedColor: "#10b981", progressSelectedColor: "#059669" },
    },
    {
      id: "fe-components",
      name: "Component Library",
      type: "task" as const,
      start: d(3, 20),
      end: d(4, 4),
      progress: 20,
      project: "proj-frontend",
      dependencies: ["fe-scaffold", "design-system"],
      styles: { backgroundColor: "#34d399", progressColor: "#10b981", backgroundSelectedColor: "#10b981", progressSelectedColor: "#059669" },
    },
    {
      id: "fe-pages",
      name: "Page Implementation",
      type: "task" as const,
      start: d(4, 1),
      end: d(4, 15),
      progress: 0,
      project: "proj-frontend",
      dependencies: ["fe-components", "mockups"],
      styles: { backgroundColor: "#6ee7b7", progressColor: "#34d399", backgroundSelectedColor: "#34d399", progressSelectedColor: "#10b981" },
    },
    {
      id: "fe-api",
      name: "API Integration",
      type: "task" as const,
      start: d(4, 11),
      end: d(4, 22),
      progress: 0,
      project: "proj-frontend",
      dependencies: ["fe-pages", "api-core"],
      styles: { backgroundColor: "#6ee7b7", progressColor: "#34d399", backgroundSelectedColor: "#34d399", progressSelectedColor: "#10b981" },
    },
    {
      id: "fe-testing",
      name: "Frontend Testing",
      type: "task" as const,
      start: d(4, 18),
      end: d(4, 29),
      progress: 0,
      project: "proj-frontend",
      dependencies: ["fe-api"],
      styles: { backgroundColor: "#a7f3d0", progressColor: "#6ee7b7", backgroundSelectedColor: "#6ee7b7", progressSelectedColor: "#34d399" },
    },

    // Project: Launch
    {
      id: "proj-launch",
      name: "Launch",
      type: "project" as const,
      start: d(4, 25),
      end: d(5, 12),
      progress: 0,
      hideChildren: false,
      styles: { backgroundColor: "#ef4444", progressColor: "#dc2626", backgroundSelectedColor: "#b91c1c", progressSelectedColor: "#991b1b" },
    },
    {
      id: "staging",
      name: "Staging Deployment",
      type: "task" as const,
      start: d(4, 25),
      end: d(4, 29),
      progress: 0,
      project: "proj-launch",
      dependencies: ["fe-testing", "perf-opt"],
      styles: { backgroundColor: "#f87171", progressColor: "#ef4444", backgroundSelectedColor: "#ef4444", progressSelectedColor: "#dc2626" },
    },
    {
      id: "uat",
      name: "UAT Testing",
      type: "task" as const,
      start: d(4, 29),
      end: d(5, 5),
      progress: 0,
      project: "proj-launch",
      dependencies: ["staging"],
      styles: { backgroundColor: "#f87171", progressColor: "#ef4444", backgroundSelectedColor: "#ef4444", progressSelectedColor: "#dc2626" },
    },
    {
      id: "bugfix",
      name: "Bug Fixes & Polish",
      type: "task" as const,
      start: d(5, 1),
      end: d(5, 8),
      progress: 0,
      project: "proj-launch",
      dependencies: ["uat"],
      styles: { backgroundColor: "#fca5a5", progressColor: "#f87171", backgroundSelectedColor: "#f87171", progressSelectedColor: "#ef4444" },
    },
    {
      id: "prod-deploy",
      name: "Production Deploy",
      type: "task" as const,
      start: d(5, 8),
      end: d(5, 10),
      progress: 0,
      project: "proj-launch",
      dependencies: ["bugfix"],
      styles: { backgroundColor: "#fca5a5", progressColor: "#f87171", backgroundSelectedColor: "#f87171", progressSelectedColor: "#ef4444" },
    },
    {
      id: "go-live",
      name: "Go Live!",
      type: "milestone" as const,
      start: d(5, 12),
      end: d(5, 12),
      progress: 0,
      project: "proj-launch",
      dependencies: ["prod-deploy"],
      styles: { backgroundColor: "#dc2626", backgroundSelectedColor: "#991b1b", progressColor: "#dc2626", progressSelectedColor: "#991b1b" },
    },
  ];
}

// ─── SVAR React Gantt Tasks ─────────────────────────────────────────────────

export function getSvarGanttData() {
  const tasks = [
    // Summary: Discovery
    { id: 1, text: "Discovery & Planning", start: d(2, 2), end: d(2, 20), type: "summary", open: true, parent: 0, progress: 85 },
    { id: 2, text: "Stakeholder Interviews", start: d(2, 2), end: d(2, 6), type: "task", parent: 1, progress: 100 },
    { id: 3, text: "Requirements Gathering", start: d(2, 6), end: d(2, 13), type: "task", parent: 1, progress: 100 },
    { id: 4, text: "Technical Assessment", start: d(2, 9), end: d(2, 16), type: "task", parent: 1, progress: 85 },
    { id: 5, text: "Risk Analysis", start: d(2, 13), end: d(2, 18), type: "task", parent: 1, progress: 70 },
    { id: 6, text: "Charter Sign-off", start: d(2, 20), end: d(2, 20), type: "milestone", parent: 1, progress: 0 },

    // Summary: Design
    { id: 10, text: "UX/UI Design", start: d(2, 20), end: d(3, 17), type: "summary", open: true, parent: 0, progress: 35 },
    { id: 11, text: "Wireframes & User Flows", start: d(2, 20), end: d(2, 30), type: "task", parent: 10, progress: 60 },
    { id: 12, text: "Design System Setup", start: d(2, 25), end: d(3, 4), type: "task", parent: 10, progress: 40 },
    { id: 13, text: "High-Fidelity Mockups", start: d(2, 30), end: d(3, 10), type: "task", parent: 10, progress: 30 },
    { id: 14, text: "Interactive Prototype", start: d(3, 7), end: d(3, 14), type: "task", parent: 10, progress: 10 },
    { id: 15, text: "Design Approval", start: d(3, 17), end: d(3, 17), type: "milestone", parent: 10, progress: 0 },

    // Summary: Backend
    { id: 20, text: "Backend Development", start: d(3, 6), end: d(4, 22), type: "summary", open: true, parent: 0, progress: 15 },
    { id: 21, text: "Database Schema Design", start: d(3, 6), end: d(3, 13), type: "task", parent: 20, progress: 50 },
    { id: 22, text: "Auth & IAM Service", start: d(3, 13), end: d(3, 24), type: "task", parent: 20, progress: 25 },
    { id: 23, text: "Core API Endpoints", start: d(3, 13), end: d(4, 1), type: "task", parent: 20, progress: 15 },
    { id: 24, text: "3rd Party Integrations", start: d(3, 27), end: d(4, 11), type: "task", parent: 20, progress: 0 },
    { id: 25, text: "Backend Testing & QA", start: d(4, 4), end: d(4, 18), type: "task", parent: 20, progress: 0 },
    { id: 26, text: "Performance Optimization", start: d(4, 11), end: d(4, 22), type: "task", parent: 20, progress: 0 },

    // Summary: Frontend
    { id: 30, text: "Frontend Development", start: d(3, 17), end: d(4, 29), type: "summary", open: true, parent: 0, progress: 8 },
    { id: 31, text: "Project Scaffolding", start: d(3, 17), end: d(3, 22), type: "task", parent: 30, progress: 80 },
    { id: 32, text: "Component Library", start: d(3, 20), end: d(4, 4), type: "task", parent: 30, progress: 20 },
    { id: 33, text: "Page Implementation", start: d(4, 1), end: d(4, 15), type: "task", parent: 30, progress: 0 },
    { id: 34, text: "API Integration", start: d(4, 11), end: d(4, 22), type: "task", parent: 30, progress: 0 },
    { id: 35, text: "Frontend Testing", start: d(4, 18), end: d(4, 29), type: "task", parent: 30, progress: 0 },

    // Summary: Launch
    { id: 40, text: "Launch", start: d(4, 25), end: d(5, 12), type: "summary", open: true, parent: 0, progress: 0 },
    { id: 41, text: "Staging Deployment", start: d(4, 25), end: d(4, 29), type: "task", parent: 40, progress: 0 },
    { id: 42, text: "UAT Testing", start: d(4, 29), end: d(5, 5), type: "task", parent: 40, progress: 0 },
    { id: 43, text: "Bug Fixes & Polish", start: d(5, 1), end: d(5, 8), type: "task", parent: 40, progress: 0 },
    { id: 44, text: "Production Deploy", start: d(5, 8), end: d(5, 10), type: "task", parent: 40, progress: 0 },
    { id: 45, text: "Go Live!", start: d(5, 12), end: d(5, 12), type: "milestone", parent: 40, progress: 0 },
  ];

  const links = [
    // Discovery deps
    { id: 1, source: 2, target: 3, type: "e2s" },
    { id: 2, source: 2, target: 4, type: "e2s" },
    { id: 3, source: 3, target: 5, type: "e2s" },
    { id: 4, source: 5, target: 6, type: "e2s" },
    { id: 5, source: 4, target: 6, type: "e2s" },

    // Design deps
    { id: 10, source: 6, target: 11, type: "e2s" },
    { id: 11, source: 11, target: 12, type: "e2s" },
    { id: 12, source: 11, target: 13, type: "e2s" },
    { id: 13, source: 13, target: 14, type: "e2s" },
    { id: 14, source: 12, target: 14, type: "e2s" },
    { id: 15, source: 14, target: 15, type: "e2s" },

    // Backend deps
    { id: 20, source: 3, target: 21, type: "e2s" },
    { id: 21, source: 21, target: 22, type: "e2s" },
    { id: 22, source: 21, target: 23, type: "e2s" },
    { id: 23, source: 23, target: 24, type: "e2s" },
    { id: 24, source: 22, target: 25, type: "e2s" },
    { id: 25, source: 23, target: 25, type: "e2s" },
    { id: 26, source: 25, target: 26, type: "e2s" },

    // Frontend deps
    { id: 30, source: 15, target: 31, type: "e2s" },
    { id: 31, source: 31, target: 32, type: "e2s" },
    { id: 32, source: 12, target: 32, type: "e2s" },
    { id: 33, source: 32, target: 33, type: "e2s" },
    { id: 34, source: 13, target: 33, type: "e2s" },
    { id: 35, source: 33, target: 34, type: "e2s" },
    { id: 36, source: 23, target: 34, type: "e2s" },
    { id: 37, source: 34, target: 35, type: "e2s" },

    // Launch deps
    { id: 40, source: 35, target: 41, type: "e2s" },
    { id: 41, source: 26, target: 41, type: "e2s" },
    { id: 42, source: 41, target: 42, type: "e2s" },
    { id: 43, source: 42, target: 43, type: "e2s" },
    { id: 44, source: 43, target: 44, type: "e2s" },
    { id: 45, source: 44, target: 45, type: "e2s" },
  ];

  return { tasks, links };
}

// ─── DHTMLX Gantt Tasks ─────────────────────────────────────────────────────

export function getDhtmlxGanttData() {
  function fmt(month: number, day: number): string {
    const m = String(month + 1).padStart(2, "0");
    const dd = String(day).padStart(2, "0");
    return `2026-${m}-${dd} 00:00`;
  }

  const data = [
    // Discovery
    { id: 1, text: "Discovery & Planning", start_date: fmt(2, 2), duration: 14, type: "project", open: true, progress: 0.85 },
    { id: 2, text: "Stakeholder Interviews", start_date: fmt(2, 2), duration: 4, parent: 1, progress: 1.0 },
    { id: 3, text: "Requirements Gathering", start_date: fmt(2, 6), duration: 5, parent: 1, progress: 1.0 },
    { id: 4, text: "Technical Assessment", start_date: fmt(2, 9), duration: 5, parent: 1, progress: 0.85 },
    { id: 5, text: "Risk Analysis", start_date: fmt(2, 13), duration: 3, parent: 1, progress: 0.7 },
    { id: 6, text: "Charter Sign-off", start_date: fmt(2, 20), duration: 0, type: "milestone", parent: 1, progress: 0 },

    // Design
    { id: 10, text: "UX/UI Design", start_date: fmt(2, 20), duration: 20, type: "project", open: true, progress: 0.35 },
    { id: 11, text: "Wireframes & User Flows", start_date: fmt(2, 20), duration: 8, parent: 10, progress: 0.6 },
    { id: 12, text: "Design System Setup", start_date: fmt(2, 25), duration: 8, parent: 10, progress: 0.4 },
    { id: 13, text: "High-Fidelity Mockups", start_date: fmt(2, 30), duration: 8, parent: 10, progress: 0.3 },
    { id: 14, text: "Interactive Prototype", start_date: fmt(3, 7), duration: 5, parent: 10, progress: 0.1 },
    { id: 15, text: "Design Approval", start_date: fmt(3, 17), duration: 0, type: "milestone", parent: 10, progress: 0 },

    // Backend
    { id: 20, text: "Backend Development", start_date: fmt(3, 6), duration: 35, type: "project", open: true, progress: 0.15 },
    { id: 21, text: "Database Schema Design", start_date: fmt(3, 6), duration: 5, parent: 20, progress: 0.5 },
    { id: 22, text: "Auth & IAM Service", start_date: fmt(3, 13), duration: 8, parent: 20, progress: 0.25 },
    { id: 23, text: "Core API Endpoints", start_date: fmt(3, 13), duration: 14, parent: 20, progress: 0.15 },
    { id: 24, text: "3rd Party Integrations", start_date: fmt(3, 27), duration: 10, parent: 20, progress: 0 },
    { id: 25, text: "Backend Testing & QA", start_date: fmt(4, 4), duration: 10, parent: 20, progress: 0 },
    { id: 26, text: "Performance Optimization", start_date: fmt(4, 11), duration: 8, parent: 20, progress: 0 },

    // Frontend
    { id: 30, text: "Frontend Development", start_date: fmt(3, 17), duration: 30, type: "project", open: true, progress: 0.08 },
    { id: 31, text: "Project Scaffolding", start_date: fmt(3, 17), duration: 3, parent: 30, progress: 0.8 },
    { id: 32, text: "Component Library", start_date: fmt(3, 20), duration: 10, parent: 30, progress: 0.2 },
    { id: 33, text: "Page Implementation", start_date: fmt(4, 1), duration: 10, parent: 30, progress: 0 },
    { id: 34, text: "API Integration", start_date: fmt(4, 11), duration: 8, parent: 30, progress: 0 },
    { id: 35, text: "Frontend Testing", start_date: fmt(4, 18), duration: 8, parent: 30, progress: 0 },

    // Launch
    { id: 40, text: "Launch", start_date: fmt(4, 25), duration: 14, type: "project", open: true, progress: 0 },
    { id: 41, text: "Staging Deployment", start_date: fmt(4, 25), duration: 3, parent: 40, progress: 0 },
    { id: 42, text: "UAT Testing", start_date: fmt(4, 29), duration: 5, parent: 40, progress: 0 },
    { id: 43, text: "Bug Fixes & Polish", start_date: fmt(5, 1), duration: 5, parent: 40, progress: 0 },
    { id: 44, text: "Production Deploy", start_date: fmt(5, 8), duration: 2, parent: 40, progress: 0 },
    { id: 45, text: "Go Live!", start_date: fmt(5, 12), duration: 0, type: "milestone", parent: 40, progress: 0 },
  ];

  const links = [
    { id: 1, source: 2, target: 3, type: "0" },
    { id: 2, source: 2, target: 4, type: "0" },
    { id: 3, source: 3, target: 5, type: "0" },
    { id: 4, source: 5, target: 6, type: "0" },
    { id: 5, source: 4, target: 6, type: "0" },

    { id: 10, source: 6, target: 11, type: "0" },
    { id: 11, source: 11, target: 12, type: "0" },
    { id: 12, source: 11, target: 13, type: "0" },
    { id: 13, source: 13, target: 14, type: "0" },
    { id: 14, source: 12, target: 14, type: "0" },
    { id: 15, source: 14, target: 15, type: "0" },

    { id: 20, source: 3, target: 21, type: "0" },
    { id: 21, source: 21, target: 22, type: "0" },
    { id: 22, source: 21, target: 23, type: "0" },
    { id: 23, source: 23, target: 24, type: "0" },
    { id: 24, source: 22, target: 25, type: "0" },
    { id: 25, source: 23, target: 25, type: "0" },
    { id: 26, source: 25, target: 26, type: "0" },

    { id: 30, source: 15, target: 31, type: "0" },
    { id: 31, source: 31, target: 32, type: "0" },
    { id: 32, source: 12, target: 32, type: "0" },
    { id: 33, source: 32, target: 33, type: "0" },
    { id: 34, source: 13, target: 33, type: "0" },
    { id: 35, source: 33, target: 34, type: "0" },
    { id: 36, source: 23, target: 34, type: "0" },
    { id: 37, source: 34, target: 35, type: "0" },

    { id: 40, source: 35, target: 41, type: "0" },
    { id: 41, source: 26, target: 41, type: "0" },
    { id: 42, source: 41, target: 42, type: "0" },
    { id: 43, source: 42, target: 43, type: "0" },
    { id: 44, source: 43, target: 44, type: "0" },
    { id: 45, source: 44, target: 45, type: "0" },
  ];

  return { data, links };
}
